### PR TITLE
resolve #1039 - add user page link in account dropdown

### LINKED ISSUE #1039: Add User Page menu link into User menu in Editor
Probably the right link text will by "My Files", given we haven't come to agreement on calling them Sessions.

### PR DESCRIPTION
**Pull request by gmarinov**
also removes old unused css

### CODE REVIEW

**Comment by kschzt** [comment]
lgtm - @mattatgit have you reviewed this?

**Comment by mattatgit** [comment]
no, i wasn't aware anything had been implemented for it yet. Where can i check it out ? Seems pretty simple though – just adding another link to the user icon menu dropdown. So long as its styled same as the other 2, i'm ok with it.

**Comment by gmarinov** [comment]
that's on my subdomain to look at. screenshot below.

screen shot 2016-02-02 at 13 08 38

**Comment by mattatgit** [comment]
Did look on your domain, but couldn't see it. But going by the screenshot, yep, works for me.

**Pull request merged**
