### PR TITLE
new homepage on fresh develop

### PR DESCRIPTION
**Pull request by imgrby**

### CODE REVIEW

**Comment by gmarinov** [comment]
issues found:
- the images are insufficient resolution at 140px, please change to retina resolution jpegs
- on Safari OSX the transitions on the team briefly flash dark squares around the circles.
- layout issues on iPhone 4s (low priority) - the "meet the team" button is cut off through the middle.

**Comment by kschzt** [comment]
should have an "Open the Editor" link on mobile?

**Comment by imgrby** [comment]
please ask Matt for exact 280x280px jpg files of team pictures

**Comment by imgrby** [comment]
added editor link to footer

**Comment by kschzt** [comment]
landed manually to master & pulled to develop.

**Pull request closed without merging**
