### PR TITLE
Reference slots in a Connection by name; resolves #1049

### LINKED ISSUE #1049: Refer to slots by name instead of index

### PR DESCRIPTION
**Pull request by kschzt**

### CODE REVIEW

**Comment by kkananen** [comment]
overall looks good but as it's a large change, I'm concerned about test coverage. Tests to check that all plugins have only valid slot names? Anything else we could test for?

**Comment by kschzt** [comment]
@kkananen there is a check in https://github.com/vizorvr/vizor/blob/slotuid/browser/scripts/node.js#L59

**Comment by kkananen** [comment]
lgtm

**Comment by kschzt** [comment]
**this will require running `node tools/migration/0.6.0/run.js` to convert existing data, graphs, presets to the new format**

**Pull request merged**
