### PR TITLE
Patches lib: promote exact match to the top of search results

### PR DESCRIPTION
**Pull request by imgrby**
waffle 549

### CODE REVIEW

**Comment by kschzt** [comment]
lgtm

**Comment by imgrby** [comment]
will it work with 500 & 250 instead of 1000 & 500?

**Comment by kschzt** [comment]
@imgrby try it - `mocha --watch browser/test/unit/collapsibleSelectControl`

**Comment by imgrby** [comment]
fixed. now promotes result of exact length too, e.g. typing "Not", expecting "Not", first was "Not equal", now - "Not".

**Comment by kschzt** [comment]
lgtm

**Pull request merged**
